version: '3'
services:
  node:
    container_name: task_manager_node
    image: node:20.10.0
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "yarn run db:create-schema && yarn run start:dev"
    depends_on:
      - db
    ports:
      - '${APP_PORT}:3008'

  redis:
    container_name: task_manager_redis
    image: redis:7.2
    ports:
      - "${REDIS_PORT}:6379"

  db:
    container_name: task_manager_db
    image: mariadb:11.2.2
    restart: always
    volumes:
      - ./.docker/mariadb/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '${MARIADB_PORT}:3306'

  phpmyadmin:
    container_name: task_manager_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: task_manager_db
